server:
   port: 8080

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://IP:端口号//服务名
    username: admin
    password: admin

mybatis:
  typt-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
